# A simple numerical example of PCA:

In [54]:
import numpy as np
from numpy.linalg import svd
np.set_printoptions(precision=2)

## Step 0: Generating a sample matrix

In [55]:
X = np.array([[1, 1, 1, 0, 0], 
              [2, 2, 2, 0, 0], 
              [1, 1, 1, 0, 0], 
              [5, 5, 5, 0, 0], 
              [1, 1, 0, 2, 2], 
              [0, 0, 0, 3, 3], 
              [0, 0, 0, 1, 1]], dtype=np.float32)


## Step1: Zero-centering data

In [56]:
mu = np.mean(X, 0)
X_norm = X - mu
print('mu = ', mu)
print('X_norm =')
print(X_norm)

mu =  [1.43 1.43 1.29 0.86 0.86]
X_norm =
[[-0.43 -0.43 -0.29 -0.86 -0.86]
 [ 0.57  0.57  0.71 -0.86 -0.86]
 [-0.43 -0.43 -0.29 -0.86 -0.86]
 [ 3.57  3.57  3.71 -0.86 -0.86]
 [-0.43 -0.43 -1.29  1.14  1.14]
 [-1.43 -1.43 -1.29  2.14  2.14]
 [-1.43 -1.43 -1.29  0.14  0.14]]


## Step2: computing sigma (covariance matrix)

In [57]:
m = X_norm.shape[0]
sigma = (X_norm.T @ X_norm) / m
print('sigma =')
print(sigma)

sigma =
[[ 2.53  2.53  2.59 -0.94 -0.94]
 [ 2.53  2.53  2.59 -0.94 -0.94]
 [ 2.59  2.59  2.78 -1.1  -1.1 ]
 [-0.94 -0.94 -1.1   1.27  1.27]
 [-0.94 -0.94 -1.1   1.27  1.27]]


## Step3: computing SVD

In [58]:
U, S, V = svd(sigma)
print ('U : ')
print (U)
print ('S : ')
print (S)

U : 
[[-5.27e-01 -2.45e-01  4.02e-01 -7.07e-01 -7.03e-17]
 [-5.27e-01 -2.45e-01  4.02e-01  7.07e-01  3.88e-17]
 [-5.56e-01 -1.46e-01 -8.18e-01  6.91e-15 -7.46e-19]
 [ 2.59e-01 -6.55e-01 -5.94e-02  6.75e-16 -7.07e-01]
 [ 2.59e-01 -6.55e-01 -5.94e-02  5.64e-16  7.07e-01]]
S : 
[8.72e+00 1.58e+00 6.69e-02 2.24e-16 0.00e+00]


## Step4: Project data

In [59]:
X_proj = X_norm @ U[:, 3]
print (X_proj)

[-3.04e-15  3.87e-15 -3.04e-15  2.46e-14 -7.46e-15 -6.22e-15 -8.70e-15]


## This is the whol process in a madule:

In [60]:
def PCA(X, k=3):
    """ 
    Arguments:
        - X: data matrix - numpy array of shape (m, n)
        - k: number of components
        
    Returns:
       - Projection of X into a k-d space of principal components
    
    """
    m = X.shape[0]
    
    Xn = X - X.mean(axis=0)   # STEP 1: zero-center data (remove mean)          
    Sigma = (Xn.T @ Xn) / m   # STEP 2: compute covariance matrix
    U, S, VT = svd(Sigma)     # STEP 3: Singular Value Decomposition
    print ('U : ')
    print (U)
    print ('S : ')
    print (S)
    print ('PCA:')
    X_proj = Xn @ U[:, :k]    # project data on U
    return X_proj

In [61]:
X = np.array([[1, 1, 1, 0, 0], 
              [2, 2, 2, 0, 0], 
              [1, 1, 1, 0, 0], 
              [5, 5, 5, 0, 0], 
              [1, 1, 0, 2, 2], 
              [0, 0, 0, 3, 3], 
              [0, 0, 0, 1, 1]], dtype=np.float32)


print (PCA(X, 3))

U : 
[[-5.27e-01 -2.45e-01  4.02e-01 -7.07e-01 -7.03e-17]
 [-5.27e-01 -2.45e-01  4.02e-01  7.07e-01  3.88e-17]
 [-5.56e-01 -1.46e-01 -8.18e-01  6.91e-15 -7.46e-19]
 [ 2.59e-01 -6.55e-01 -5.94e-02  6.75e-16 -7.07e-01]
 [ 2.59e-01 -6.55e-01 -5.94e-02  5.64e-16  7.07e-01]]
S : 
[8.72e+00 1.58e+00 6.69e-02 2.24e-16 0.00e+00]
PCA:
[[ 0.17  1.37 -0.01]
 [-1.44  0.74 -0.02]
 [ 0.17  1.37 -0.01]
 [-6.28 -1.17 -0.06]
 [ 1.76 -1.1   0.57]
 [ 3.33 -1.92 -0.35]
 [ 2.3   0.7  -0.11]]
